### ISSUE TITLE
Package installation fails

### ISSUE THREAD

**Issue by irimiab** [kronometrix/mqtt#1]
I think there is a broken reference in the package, related with the `rc.d` script. Here's what happens when trying to install the package:

```sh
# pkg add kmqtt-1.0.0-freebsd12.0-amd64.txz
Installing kmqtt-1.0.0...
Extracting kmqtt-1.0.0: 100%
cp: /opt/kronometrix/avmet/etc/rc/kmqtt: No such file or directory
/bin/sh: /etc/rc.d/kmqtt: not found
```

Tried to fix them manually, but it still doesn't work.

**Comment by sparvu** [comment]
fixed in latest 1.0.1 release. New packages are pushed to the SSH gateway
