### ISSUE TITLE
Pakage installation wrong ownership

### ISSUE THREAD

**Issue by irimiab** [kronometrix/mqtt#2]
On my machine, the folder `/opt/kronometrix/mqtt` had as ownership `root:krmx`. This caused the `nginx` process to fail when starting because it didn't have the necessary rights to create the logs.

I fixed changing ownership to `krmx:krmx`.

Please fix this in the package as well.

**Comment by sparvu** [comment]
this hsould be just fine on the default package. not sure how u ended up with root:kmx ... re-open if you have still issues using kmqtt-1.0.2
