### ISSUE TITLE
Default nginx.conf file

### ISSUE THREAD

**Issue by irimiab** [kronometrix/mqtt#3]
This is the `nginx.conf` file needed for MQTT (currently):
```conf
worker_processes  1;
error_log logs/error.log;

events {
    use kqueue;
    worker_connections 1024;
    multi_accept on;
}

stream {
    lua_package_path ";;${prefix}../app/?.lua;";
    lua_code_cache on;

    resolver 8.8.8.8;

    init_by_lua_file "../app/init.lua";
    init_worker_by_lua_file "../app/main.lua";
}
```

Will also need this library: https://github.com/xHasKx/luamqtt
More precisely, the folder "mqtt" from the above GitHub repository must be placed in `.../mqtt/lualib/`

Thanks

**Comment by sparvu** [comment]
For future try to learn new DNS servers as well not only Google's.
