### ISSUE TITLE
Can't clone and use repository since it include symlinks which conflict with dev system

### ISSUE THREAD

**Issue by irimiab** [kronometrix/mqtt#5]
In this repository you included symlinks which, when cloned on my system, are conflicting with the installed package.

Can you please fix this? Did you intentionally include the symlinks, or you intended to include the actual file/folder?

**Comment by sparvu** [comment]
* this is how the package is structured to know what binaries it needs and use

 * why are you conflicting with this ? same thing is also on the K platform 

 * excuse me, are you working under /opt/kronometrix directly ?? 

 * /opt/kronometrix is used for deployments 

I cant fix the repo. All Kronometrix packages are built this way.

**Comment by irimiab** [comment]
Offer me a solution. When I commit, the references are changed.
I'm not working in /opt/kronometrix, no. But it doesn't matter. When I clone, those references (symlinks) will point towards my installation. This differs from your installation. When I commit, all these differences go to GitHub. This will change your setup.

Please check the branch "irimiab". See what's changed and if it's OK. It's fine by me, but will break your setup.

**Comment by sparvu** [comment]
im not following it. let me finish some incident we have in mail production and come back to you. how have u worked with avmet repo ? this is nothing different. you just need to clone create the app and commit to the app directory the app.

**Comment by irimiab** [comment]
Fixed

Managed to set a property for Git to not follow symlinks: `core.symlinks=false`
Also, I set Git to ignore file modes, so now all looks good.

**Comment by sparvu** [comment]
good
